name: CI
on:
  pull_request: {}
  push: {}
permissions: write-all
jobs:
  # ================
  # BUILD AND TEST JOB
  # ================
  test:
    name: Build & Test
    strategy:
      matrix:
        # optionally test/build across multiple platforms/Go-versions
        go-version: ['1.20']
        platform: [ubuntu-latest] # , macos-latest, windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build
        run: go build -v -o /dev/null .
      - name: Test
        run: go test -v ./...